### ISSUE TITLE
MediaElementRenderer [Bug] 

### ISSUE THREAD

**Issue by ghaith100994** [xamarin/Xamarin.Forms#9961]
### Steps to Reproduce

1. Add Photos and videos to page with carousel view 
2. move fast between pages 
3. error happen

03-15 02:33:05.212 E/AppCenterCrashes(20867): Unhandled Exception from source=AppDomain
03-15 02:33:05.212 E/AppCenterCrashes(20867): System.ObjectDisposedException: Cannot access a disposed object.
03-15 02:33:05.212 E/AppCenterCrashes(20867): Object name: 'Xamarin.Forms.Platform.Android.MediaElementRenderer'.
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <e7e2d009b69d4e5f9a00e6ee600b8a8e>:0 
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Android.Views.ViewGroup.RemoveView (Android.Views.View view) [0x00031] in <11f101b564894ca7af6c482ddc51c698>:0 
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Xamarin.Forms.Platform.Android.MediaElementRenderer.ReleaseControl () [0x0001f] in d:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\MediaElementRenderer.cs:475 
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Xamarin.Forms.Platform.Android.MediaElementRenderer.Dispose (System.Boolean disposing) [0x00010] in d:\a\1\s\Xamarin.Forms.Platform.Android\FastRenderers\MediaElementRenderer.cs:209 
03-15 02:33:05.212 E/AppCenterCrashes(20867):   at Java.Lang.Object.Finalize () [0x00048] in <11f101b564894ca7af6c482ddc51c698>:0

**Comment by jfversluis** [comment]
Hey @ghaith100994 thanks for the issue.

I am a bit confused though. In the title you talk about `MediaElement` and in the repro about a `CarouselView`. Are you using a `MediaElement` in a `CarouselView`?

Could you please add more data as suggested by the bug template. Is there any reason you did not use that? We would like to have some more information about which version of Android this happens on, what you are doing, what version of Xamarin.Forms etc. 

It would also be _really_ helpful to have a reproduction project that shows this bug.

Thanks!

**Comment by ghaith100994** [comment]
Thanks for replay
yes I added A custom Carousel View that have picture and video 
when switching fast between them 
this error happen
` ` `  
<ContentPage.Resources>
        <DataTemplate x:Key="CarouselImageView">
            <ContentView>
                <AbsoluteLayout  AutomationProperties.HelpText="{Binding Image.AltText}"
                                            AutomationProperties.IsInAccessibleTree="True"
                                            VerticalOptions="FillAndExpand">
                    <ffimageloading:CachedImage AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All"
                                                Aspect="AspectFill"
                                                CacheDuration="50"
                                                HorizontalOptions="FillAndExpand"
                                                IsVisible="{Binding Image.IsImage}"
                                                RetryCount="1"
                                                RetryDelay="10"
                                                Source="{Binding Image.ImageUrl}"
                                                VerticalOptions="FillAndExpand" />
                    <AbsoluteLayout Padding="10,30,10,30"
                                                AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All">

                        <StackLayout Padding="0,130,0,0"
                                                 AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                 AbsoluteLayout.LayoutFlags="All"
                                                 HorizontalOptions="CenterAndExpand"
                                                 Orientation="Vertical"
                                                 Spacing="0"
                                                 VerticalOptions="Start">
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="35"
                                           FontFamily="{StaticResource Gothic}"
                                           HorizontalTextAlignment="Center"
                                           Text="{Binding FirstLine}"
                                           TextColor="White"/>
                            <Label Margin="0,2,0,0"
                                           AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="40"
                                           HorizontalTextAlignment="Center"
                                           FontFamily="{StaticResource Gothic}"
                                           Text="{Binding SecondLine}"
                                           TextColor="White"/>
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                               ClassId="{Binding Link}"
                                               FontSize="18"
                                               HorizontalTextAlignment="Center"
                                               CharacterSpacing="1.8" 
                                               FontFamily="{StaticResource Gothic}"
                                               Text="{Binding LinkText}"
                                               TextColor="White">
                                <Label.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.OpenUrlInBrowserCommand,Source={x:Reference dashboardPage}}" CommandParameter="{Binding Link}"/>
                                </Label.GestureRecognizers>
                            </Label>
                        </StackLayout>
                    </AbsoluteLayout>
                </AbsoluteLayout>
            </ContentView>
        </DataTemplate>
        <DataTemplate x:Key="CarouselVideoView">
            <ContentView>
                <AbsoluteLayout AutomationProperties.HelpText="{Binding Image.AltText}"
                                            AutomationProperties.IsInAccessibleTree="True"
                                            VerticalOptions="FillAndExpand">
                    
                    
                    <MediaElement Source="{Binding Image.ImageUrl}"
                              IsLooping="True"
                              AbsoluteLayout.LayoutBounds="0,0,1,1"
                              AbsoluteLayout.LayoutFlags="All"
                              ShowsPlaybackControls="False"
                              HorizontalOptions="FillAndExpand"
                              AutoPlay="True"
                              BackgroundColor="Black"
                              AutomationProperties.HelpText="{Translate:Translate AltText}"
                              AutomationProperties.IsInAccessibleTree="true"
                              Aspect="AspectFill"
                              VerticalOptions="FillAndExpand"
                              IsVisible="{Binding Image.IsVideo}"/>
                    <AbsoluteLayout Padding="10,30,10,30"
                                                AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All">

                        <StackLayout Padding="0,130,0,0"
                                                 AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                 AbsoluteLayout.LayoutFlags="All"
                                                 HorizontalOptions="CenterAndExpand"
                                                 Orientation="Vertical"
                                                 Spacing="0"
                                                 VerticalOptions="Start">
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="35"
                                           FontFamily="{StaticResource Gothic}"
                                           HorizontalTextAlignment="Center"
                                           Text="{Binding FirstLine}"
                                           TextColor="White"/>
                            <Label Margin="0,2,0,0"
                                           AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="40"
                                           HorizontalTextAlignment="Center"
                                           FontFamily="{StaticResource Gothic}"
                                           Text="{Binding SecondLine}"
                                           TextColor="White"/>
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                               ClassId="{Binding Link}"
                                               FontSize="18"
                                               HorizontalTextAlignment="Center"
                                               CharacterSpacing="1.8" 
                                               FontFamily="{StaticResource Gothic}"
                                               Text="{Binding LinkText}"
                                               TextColor="White">
                                <Label.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.OpenUrlInBrowserCommand,Source={x:Reference dashboardPage}}" CommandParameter="{Binding Link}"/>
                                </Label.GestureRecognizers>
                            </Label>
                        </StackLayout>
                    </AbsoluteLayout>
                </AbsoluteLayout>
            </ContentView>
        </DataTemplate>

        <controls:CarouselSelectorDataTemplate x:Key="CarouselSelector"
                                               CarouselImageView="{StaticResource CarouselImageView}"
                                               CarouselVideoView="{StaticResource CarouselVideoView}" />
    </ContentPage.Resources>
```

**Comment by ghaith100994** [comment]
Thanks for replay 
yes iam using carousel view with media element 
and this what happen
I Have Tabbed Page with two Page 
the first page unimportant but the second page is A carousel view with custom Data Template
which has photos and videos
I used to use another player and this work fine 
but when update to Media Element
This Bug Happens When switching view inside carousel view fast then go to the other page in tabbed page

**Comment by ghaith100994** [comment]
`
<DataTemplate x:Key="CarouselImageView">
            <ContentView>
                <AbsoluteLayout  AutomationProperties.HelpText="{Binding Image.AltText}"
                                            AutomationProperties.IsInAccessibleTree="True"
                                            VerticalOptions="FillAndExpand">
                    <ffimageloading:CachedImage AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All"
                                                Aspect="AspectFill"
                                                CacheDuration="50"
                                                HorizontalOptions="FillAndExpand"
                                                IsVisible="{Binding Image.IsImage}"
                                                RetryCount="1"
                                                RetryDelay="10"
                                                Source="{Binding Image.ImageUrl}"
                                                VerticalOptions="FillAndExpand" />
                    <AbsoluteLayout Padding="10,30,10,30"
                                                AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All">

                        <StackLayout Padding="0,130,0,0"
                                                 AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                 AbsoluteLayout.LayoutFlags="All"
                                                 HorizontalOptions="CenterAndExpand"
                                                 Orientation="Vertical"
                                                 Spacing="0"
                                                 VerticalOptions="Start">
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="35"
                                           FontFamily="{StaticResource Gothic}"
                                           HorizontalTextAlignment="Center"
                                           Text="{Binding FirstLine}"
                                           TextColor="White"/>
                            <Label Margin="0,2,0,0"
                                           AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="40"
                                           HorizontalTextAlignment="Center"
                                           FontFamily="{StaticResource Gothic}"
                                           Text="{Binding SecondLine}"
                                           TextColor="White"/>
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                               ClassId="{Binding Link}"
                                               FontSize="18"
                                               HorizontalTextAlignment="Center"
                                               CharacterSpacing="1.8" 
                                               FontFamily="{StaticResource Gothic}"
                                               Text="{Binding LinkText}"
                                               TextColor="White">
                                <Label.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.OpenUrlInBrowserCommand,Source={x:Reference dashboardPage}}" CommandParameter="{Binding Link}"/>
                                </Label.GestureRecognizers>
                            </Label>
                        </StackLayout>
                    </AbsoluteLayout>
                </AbsoluteLayout>
            </ContentView>
        </DataTemplate>
`

**Comment by ghaith100994** [comment]
`
        <DataTemplate x:Key="CarouselVideoView">
            <ContentView>
                <AbsoluteLayout AutomationProperties.HelpText="{Binding Image.AltText}"
                                            AutomationProperties.IsInAccessibleTree="True"
                                            VerticalOptions="FillAndExpand">
                  
                    <MediaElement Source="{Binding Image.ImageUrl}"
                              IsLooping="True"
                              AbsoluteLayout.LayoutBounds="0,0,1,1"
                              AbsoluteLayout.LayoutFlags="All"
                              ShowsPlaybackControls="False"
                              HorizontalOptions="FillAndExpand"
                              AutoPlay="True"
                              BackgroundColor="Black"
                              AutomationProperties.HelpText="{Translate:Translate AltText}"
                              AutomationProperties.IsInAccessibleTree="true"
                              Aspect="AspectFill"
                              VerticalOptions="FillAndExpand"
                              IsVisible="{Binding Image.IsVideo}"/>
                    <AbsoluteLayout Padding="10,30,10,30"
                                                AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                AbsoluteLayout.LayoutFlags="All">

                        <StackLayout Padding="0,130,0,0"
                                                 AbsoluteLayout.LayoutBounds="0,0,1,1"
                                                 AbsoluteLayout.LayoutFlags="All"
                                                 HorizontalOptions="CenterAndExpand"
                                                 Orientation="Vertical"
                                                 Spacing="0"
                                                 VerticalOptions="Start">
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="35"
                                           FontFamily="{StaticResource Gothic}"
                                           HorizontalTextAlignment="Center"
                                           Text="{Binding FirstLine}"
                                           TextColor="White"/>
                            <Label Margin="0,2,0,0"
                                           AutomationProperties.IsInAccessibleTree="True"
                                           CharacterSpacing="3"
                                           FontSize="40"
                                           HorizontalTextAlignment="Center"
                                           FontFamily="{StaticResource Gothic}"
                                           Text="{Binding SecondLine}"
                                           TextColor="White"/>
                            <Label AutomationProperties.IsInAccessibleTree="True"
                                               ClassId="{Binding Link}"
                                               FontSize="18"
                                               HorizontalTextAlignment="Center"
                                               CharacterSpacing="1.8" 
                                               FontFamily="{StaticResource Gothic}"
                                               Text="{Binding LinkText}"
                                               TextColor="White">
                                <Label.GestureRecognizers>
                                    <TapGestureRecognizer Command="{Binding Path=BindingContext.OpenUrlInBrowserCommand,Source={x:Reference dashboardPage}}" CommandParameter="{Binding Link}"/>
                                </Label.GestureRecognizers>
                            </Label>
                        </StackLayout>
                    </AbsoluteLayout>
                </AbsoluteLayout>
            </ContentView>
        </DataTemplate>

`

**Comment by MickLesk** [comment]
Hey Guys,

i get the same error with Forms 4.5. 
Take a Look here: https://github.com/xamarin/Xamarin.Forms/issues/9852


@jfversluis But we dont use CaruselView or MediaElements.

**Comment by jfversluis** [comment]
@ghaith100994 thank you for posting the code, but this still requires me to put together a lot of pieces. It will really help us get to the core faster if you can attach a runnable reproduction project.

**Comment by MickLesk** [comment]
> @ghaith100994 thank you for posting the code, but this still requires me to put together a lot of pieces. It will really help us get to the core faster if you can attach a runnable reproduction project.

I have been able to reproduce a similar error with the following repro. You are welcome to have a look at them. 

The project is from @Depechie  from the following issue: https://github.com/xamarin/Xamarin.Forms/issues/9852

Config: Release -> d8 / r8 


[SteemaTesto.zip](https://github.com/xamarin/Xamarin.Forms/files/4349919/SteemaTesto.zip)

**Comment by jfversluis** [comment]
@MickLesk I'm sorry but I don't see how this is the same problem?

**Comment by samhouts** [comment]
@ghaith100994 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!

**Comment by samt1925** [comment]
Error still continue. Same here, im using carousel view and media element together on xamarin.forms 4.8.0.1821.

**Comment by jfversluis** [comment]
@samt1925 the `MediaElement` has moved to the [Xamarin.CommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit/), please try out the code there and open an issue on that repo if there isn't an existing one already.

Thanks!
