### ISSUE TITLE
[Bug] NSException thrown when calling NSColor.ControlBackground.ToColor()

### ISSUE THREAD

**Issue by chucker** [xamarin/Xamarin.Forms#9962]
### Description
In a Xamarin Forms macOS app, the `ToColor()` extension method offers a convenient conversion from AppKit to Xamarin Forms.

However, this crashes for some colors.

### Steps to Reproduce

Given an app **MyApp** with a page **MainPage**:

```csharp
var page = new MyApp.Views.MainPage();

page.BackgroundColor = NSColor.Blue.ToColor(); // this works
page.BackgroundColor = NSColor.ControlBackground.ToColor(); // this crashes
```

### Expected Behavior

To match Apple behavior, instead of an NSException, this should throw something like an InvalidOperationException.

### Actual Behavior

This crashes:

    2020-03-15 21:38:20.189 MyApp.macOS[8260:9815189]
    *** Terminating app due to uncaught exception 'NSInvalidArgumentException',
    reason: '*** -getRed:green:blue:alpha: not valid for the NSColor Catalog
    color: System controlBackgroundColor; need to first convert colorspace.'

### Basic Information

- Version with issue: 4.5.0.356
- IDE: Visual Studio for Mac 8.4.8
- Platform Target Frameworks:
  - macOS: Xamarin.Mac Modern, SDK 10.15
- Affected Devices: MacBook Pro (Retina, 15-inch, Late 2013) on 10.15.3 (19D76)

### Workaround

Converting the color with an explicit color space works:

```csharp
NSColor controlBackground = NSColor.ControlBackground;
var convertedColor = controlBackground.UsingColorSpace(NSColorSpace.DeviceRGBColorSpace);
page.BackgroundColor = convertedColor.ToColor();
```

However, this is awkward. Perhaps `ToColor()` should have an overload that lets me specify a color space?

```csharp
page.BackgroundColor =
    NSColor.ControlBackground.ToColor(NSColorSpace.DeviceRGBColorSpace);
```

**Comment by jfversluis** [comment]
Confirmed this is happening.

We can check the color type in the `ColorExtensions.cs` with `if (color.Type == NSColorType.Catalog)` if that is true, we can throw the `InvalidOperationException`.

To make this scenario work we might consider adding an overload as suggested.

[Repro9962.zip](https://github.com/xamarin/Xamarin.Forms/files/4336910/Repro9962.zip)
