### ISSUE TITLE
Need API support to open FlyLayoutView only by tapping HamburgerIcon not by Swipe!

### ISSUE THREAD

**Issue by GnanaPriyaNamasivayam** [xamarin/Xamarin.Forms#9966]
Summary
In my application, i need to show FlyoutItems only when i tap HamburgerIcon but not through swiping left to right. Do you have any solution for this for Android & iOS. Can you enable this option using any bool property.

API Changes
Here, FlyoutLayout behaves differently for iPad & iPhone.
In iPhone - FlyLayout opens only on swiping from left dead of the screen but not on swiping middle or right of screen.
In iPad - FlyLayout opens on swiping anywhere in the shell page middle, left.
I can't use FlyLayoutBehavior as Locked in my MapViewScreen.
It will be helpful if you expose 2 different property or additional property in FlyLayout behavior to disable swipe open the FlyLayout.

or kindly provide me any code solution to achieve this requirement using renderer of Android & iOS platform to overcome this behavior.
It will be really helpful. Thanks in advance...

**Comment by GnanaPriyaNamasivayam** [comment]
I already created a query, but it was closed. Please consider this request again and provide us the API support.
FYI.
https://github.com/xamarin/Xamarin.Forms/issues/9896

**Comment by GnanaPriyaNamasivayam** [comment]
I'm glad you have added my request under consideration. Can you share a timeline regarding this API to be rolled out?

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
