### ISSUE TITLE
[Enhancement] RadioButton.ButtonSource: custom images for RadioButton

### ISSUE THREAD

**Issue by jfversluis** [xamarin/Xamarin.Forms#9968]
## Summary
Initially the `RadioButton` had an API to use a custom image for the bullet. Upon further inspection this was only implemented on Android and missing on iOS, UWP and MacOS. To not block the next release and still have `RadioButton`, the API was removed for now and this issue is here to track the progress on (re)implementing the ButtonSource API.

Related: 
 - Original PR #8910
 - Bug #9948
 - Removal PR #9967

## API Changes

Add/reenable this API in the `RadioButton`:
 - `public static readonly BindableProperty ButtonSourceProperty`
 - `public ImageSource ButtonSource { get; set; }`

## Intended Use Case
Being able to use a custom image for the `RadioButton` bullet. Through the `VisualStateManager` people are able to supply images for both the checked and unchecked state.

**Comment by rookiejava** [comment]
Hey @jfversluis, do `RadioButton` need to inherit `Button`?
If you need `Font`, `Text`, and `Border` related properties, we'd better implement `IFontElement`, `IBorderElement,` `IBorderElement` instead.

**Comment by jfversluis** [comment]
Technically it doesn't have to. This was taken over from a community PR and implemented like this. Possibly before the mentioned interfaces were available back then.

I think the way `CheckBox` was implemented would also make more sense here.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
