### ISSUE TITLE
[Bug] Tab navigation (tabstop/tabindex) doesn't work on UWP app

### ISSUE THREAD

**Issue by E75** [xamarin/Xamarin.Forms#9969]
### Description
Navigation tab (tabindex/ tabstop) doesn't work for the UWP app with a physical keyboard.
### Steps to Reproduce

1.  Create a Listview with grid what contains a label/entry
2.  Add tabindex on the entry fields (and tabstop on the labels)
3.  Build the App and navigate with the tab keyboard control (physical keyboard)

### Expected Behavior
the tab control should go to the next entry field and back to the page
### Actual Behavior
![tab navigation uwp](https://user-images.githubusercontent.com/9724772/76771751-1c924e00-67a0-11ea-9c93-72b7fe790e9d.gif)
### Basic Information

- Version with issue: X.Forms 4.5.0.356
- Last known good version: (don't know)
- IDE: VS2019 16.4.6
- Platform Target Frameworks: 
  - UWP:  1903 (Build 18362)
- Affected Devices:
UWP App
### Reproduction Link/Code

![afbeelding](https://user-images.githubusercontent.com/9724772/76769066-3af64a80-679c-11ea-8fef-bf976e4b6ec7.png)

### Workaround
Nothing

**Comment by jfversluis** [comment]
Would you be able to add a smal reproduction project or at least the code in a format that we can copy and paste instead of an image? Thanks!

**Comment by samhouts** [comment]
@E75 Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
