### ISSUE TITLE
[Bug] Delayed adding of items to ObservableCollection used in CollectionView throws null reference exception

### ISSUE THREAD

**Issue by domenk** [xamarin/Xamarin.Forms#9970]
### Description

When using CollectionView with ObservableCollection and custom DataTemplateSelector on iOS, existing items are unnecessarily "refreshed" when you add items to ObservableCollection after the CollectionView is shown. This leads to NullReferenceException in Xamarin.Forms.Platform.iOS.VerticalCell.Measure method.

Tested on iPhone 11 iOS 13.3 simulator.

On Android it works as expected.

### Steps to Reproduce

Run the attached project: [FormsBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4338830/FormsBug.zip)

File CollectionViewTest.cs contains three scenarios – comment them out accordingly.

### Expected Behavior

New items should be added to the list. Existing items should not be reloaded.

### Actual Behavior

Existing items are reloaded which throws an exception.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: /
- IDE: Visual Studio 16.4.6
- Platform Target Frameworks:
  - iOS: 13.10.0.21
  - Android: 10.1.4.0
- Affected Devices: iPhone 11 iOS 13.3 (only one tested)

**Comment by jfversluis** [comment]
For some reason I can't run your reproduction on a Mac, so find a new one attached. Seeing this happening. I tried a quick fix by adding a null check but that led to another subsequent issue it seems, so needs some more looking into. Confirmed this still happens on current nightly build.

[Repro9970.zip](https://github.com/xamarin/Xamarin.Forms/files/4338986/Repro9970.zip)

**Comment by domenk** [comment]
One observation: if delegate in DataTemplate returns new view on each call, no exception is thrown.

To reproduce, replace `return item;` in CollectionViewTestDataTemplateSelector.OnSelectTemplate with `return new Label { Text = ((Label) item).Text };`

**Comment by domenk** [comment]
It's also interesting that the DataTemplate delegate gets called 6 times on iOS, but only 3 times on Android.

iOS:
Call 1: when adding A1 – called for A1
Call 2 and 3: when adding A2 – called for A1 and A2
Call 4, 5 and 6: when adding B1 – called for A1, A2 and B1

Android:
Each call only for the item added in that moment.

**Comment by dansiegel** [comment]
This issue is something that I'm seeing in the Prism branch for Regions as we use an ObservableCollection bound to the ItemsSource. This is a critical bug that is a show stopper for anyone who is using an ObservableCollection. 

For a reproduction you can pull the `wip-regions` branch and run Prism's Xamarin.Forms E2E test app.

**Comment by hartez** [comment]
This is fixed in version 5.0.0.1931 (and possibly earlier, but that's the version I just tested against scenarios 1 and 3 in the repro project).
