### ISSUE TITLE
[Bug] Shell Can't change query property values when on the same page using GoToAsync

### ISSUE THREAD

**Issue by GeorgeVelikov** [xamarin/Xamarin.Forms#9975]
### Description

Cannot change the query properties for page X when i'm already on page X and the query property setters get hit the next time i go back to page X from some arbitrary page Y.

I would like to change the query properties of a page without having to cast Shell.Current.CurrentItem.CurrentItem as a IShellSectionController & grab the page instance of what's currently displayed on the screen.

### Steps to Reproduce

Have page X which has some query property and have some page Y

1. Go to page X
2. Use GoToAsync page X with some query property
3. Setter's won't get hit
4. Go to page Y
5. Go back to page X
6. Query property setters will be hit with the previously specified query values in step 2

### Expected Behavior

Query property setters get hit

### Actual Behavior

Query property setters don't get hit

### Basic Information

- Version with issue: Xamarin Forms 4.5
- Last known good version: None
- IDE: Visual Studio 2019
- Platform Target Frameworks (the ones I've tested): 
  - iOS:  12.2 & 13.4
  - Android: 9.1

### Screenshots

Not a visual issue

### Reproduction Link

[Issue9975.zip](https://github.com/xamarin/Xamarin.Forms/files/4339347/Issue9975.zip)

### Workaround

I can get the currently displayed page instance and call the function which the query property setter calls, but this doesn't feel very elegant.

```csharp
public Page GetCurrentlyDisplayedPageInstance() {
    ShellSection currentShellSection = Shell.Current?.CurrentItem?.CurrentItem;

    if (!(currentShellSection is IShellSectionController shellSectionController)) {
        return null;
    }

    return shellSectionController.PresentedPage;
}

. . .

SomePageType typedPage = (GetCurrentlyDisplayedPageInstance() as SomePageType);
typedPage?.SomeUIFunction();

```

**Comment by samhouts** [comment]
closed by #10176
