### ISSUE TITLE
[Bug] IsClippedToBounds is not respected on Android if <application> occurs before <uses-sdk> in manifest

### ISSUE THREAD

**Issue by domenk** [xamarin/Xamarin.Forms#9977]
### Description

IsClippedToBounds on Frame is not respected if `<application>` tag occurs before `<uses-sdk>` in AndroidManifest.xml.

Tested on Nexus 4 x86 API 23 and API 28 emulator.

### Steps to Reproduce

Run the attached project: [FormsBug.zip](https://github.com/xamarin/Xamarin.Forms/files/4339262/FormsBug.zip)

When you run the project, top corners should not be rounded. Now edit AndroidManifest.xml and move `<application>` tag below `<uses-sdk>`. Top corners should now rounded, as expected.

### Expected Behavior

Top corners of the blue box should be rounded.

### Actual Behavior

Top corners of the blue box are not rounded because Frame does not clip inner StackLayout.

### Basic Information

- Version with issue: 4.5.0.356
- Last known good version: /
- IDE: Visual Studio 16.4.6
- Platform Target Frameworks:
  - iOS: 13.10.0.21
  - Android: 10.1.4.0
- Android Support Library Version: none
- Affected Devices: tested on Nexus 4 x86 API 23 and API 28 emulator

**Comment by jfversluis** [comment]
As noted in the [Android documentation](https://developer.android.com/guide/topics/manifest/manifest-intro#filec):

> The <application> element must be the last element inside the <manifest> element.

Nothing we can do about that, sorry :)
