### ISSUE TITLE
[Bug] Xamarin.Forms ListView ScrollTo can't work on android

### ISSUE THREAD

**Issue by MackYang** [xamarin/Xamarin.Forms#9981]
### Description
listview.ScrollTo can't work on android

below is code

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:d="http://xamarin.com/schemas/2014/forms/design"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             mc:Ignorable="d"
             x:Class="XamarinDemo.LayoutTest">
    <ContentPage.Resources>
        <Style TargetType="Frame">
            <Setter Property="BackgroundColor" Value="Beige"/>
            <Setter Property="HorizontalOptions" Value="FillAndExpand"/>
            <Setter Property="Padding" Value="0"/>
        </Style>
        <Style TargetType="Label">
            <Setter Property="HorizontalOptions" Value="FillAndExpand"/>
            <Setter Property="TextColor" Value="Black"/>
            <Setter Property="BackgroundColor" Value="Blue"/>
        </Style>
    </ContentPage.Resources>
    <ContentPage.Content>
        <ListView SelectionMode="None" ItemTapped="ListView_ItemTapped" x:Name="list">
            
            <ListView.ItemsSource>
                <x:Array Type="{x:Type x:String}">
                    <x:String>aaa</x:String>
                    <x:String>bbb</x:String>
                    <x:String>ccc</x:String>
                    <x:String>aaa2</x:String>
                    <x:String>bbb3</x:String>
                    <x:String>ccc4</x:String>
                    <x:String>aaa11</x:String>
                    <x:String>bbb11</x:String>
                    <x:String>ccc11</x:String>
                    <x:String>aaa222</x:String>
                    <x:String>bbb322</x:String>
                    <x:String>ccc422</x:String>
                    <x:String>aaa33</x:String>
                    <x:String>bbb33</x:String>
                    <x:String>ccc33</x:String>
                    <x:String>aaa244</x:String>
                    <x:String>bbb344</x:String>
                    <x:String>ccc444</x:String>
                    <x:String>aaa55</x:String>
                    <x:String>bbb66</x:String>
                    <x:String>ccc66</x:String>
                    <x:String>aaa266</x:String>
                    <x:String>bbb377</x:String>
                    <x:String>ccc477</x:String>
                </x:Array>
            </ListView.ItemsSource>
        </ListView>
    </ContentPage.Content>
</ContentPage>

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;
using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace XamarinDemo
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class LayoutTest : ContentPage
    {

        public LayoutTest()
        {
            InitializeComponent();
            this.BindingContext = this;
        }

        private void ListView_ItemTapped(object sender, ItemTappedEventArgs e)
        {
            list.ScrollTo(e.Item, ScrollToPosition.Center, true);//can't work
        }
    }
}

 

### Expected Behavior
scall to screen center
### Actual Behavior
can't scroll
### Basic Information

- Version with issue:
- Last known good version:
- IDE:VS2019
- Platform Target Frameworks: 

  - Android:  

- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jfversluis** [comment]
Hey @MackYang thanks for reporting this. Could you maybe add a small reproduction sample of the code you posted? And could you please add the rest of the info like requested in the template; what Forms version are you using, which Android version, etc.

Thanks

**Comment by MackYang** [comment]
Android 9.0
XamarinForm 4.2.0.848062
Thanks

**Comment by jfversluis** [comment]
Would you be able to test on the latest stable Forms version? Also, still a reproduction project would be awesome.

**Comment by samhouts** [comment]
@MackYang Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
