### ISSUE TITLE
[Enhancement] Button background without a ripple effect on Android

### ISSUE THREAD

**Issue by domenk** [xamarin/Xamarin.Forms#9984]
## Summary
Button background on Android currently has a ripple effect when pressed.

One can avoid this effect with a custom renderer. But Button has many properties that are implemented in the background drawable: corner radius, border, pressed state. Whole BorderDrawable class in Xamarin.Forms.Platform.Android is dedicated to handle these properties.

So I suggest providing easier means of avoiding/turning off the ripple effect.

## API Changes

I see two possible approaches:

1. Add AndroidSpecific extension method that skips ripple effect in [Xamarin.Forms.Platform.Android/BorderBackgroundManager.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/BorderBackgroundManager.cs):

       var button = new Button();
       button.On<Android>().SetUseRippleEffect(false);

2. Remove `internal` modifier from `BorderDrawable` class in [Xamarin.Forms.Platform.Android/Renderers/BorderDrawable.cs](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.Android/Renderers/BorderDrawable.cs) so that it can be used in custom renderer.

**Comment by kanderson-wellbeats** [comment]
i worked around this with the following custom renderer. it could probably be made more efficient but it works (it's responding to every property change when really there are only certain properties it needs to happen for, but i didn't bother figuring out which ones they are).

```
[assembly: ExportRenderer(typeof(Button), typeof(NoRippleButtonRenderer))]
namespace Whatever
{
    public class NoRippleButtonRenderer : ButtonRenderer
    {
        public NoRippleButtonRenderer(Context context) : base(context) { }

        protected override void OnElementChanged(ElementChangedEventArgs<Button> e)
        {
            base.OnElementChanged(e);
            if (e.NewElement != null && 
                Control.Background is RippleDrawable ripple)
            {
                ripple.SetColor(ColorStateList.ValueOf(Color.Transparent));
            }
        }

        protected override void OnElementPropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            base.OnElementPropertyChanged(sender, e); 
            if (Control.Background is RippleDrawable ripple)
            {
                ripple.SetColor(ColorStateList.ValueOf(Color.Transparent));
            }
        }
    }
}
```

this allows me to use a gradient as a background and not have a ripple. furthermore, using triggers to watch IsPressed allows me to change the background to another gradient when the button is pressed, so there is still feedback for the user but not the ripple. VisualStates may be the recommended/better way of changing properties with taps but unfortunately using VisualStates causes the ripple to return, defeating my custom renderer.

**Comment by jfversluis** [comment]
Thanks for this suggestion! As Xamarin.Forms is now in maintenance mode, this will not happen anymore for Xamarin.Forms. We're only adding bugfixes and stability fixes.

If this is still important to you, make sure to check the [.NET MAUI repo](https://github.com/dotnet/maui) and see if it's already on the roadmap. If not, feel free to open a discussion to discuss a change first or open an issue with a detailed feature request. Thanks!
