### ISSUE TITLE
[Bug] Picker Background color is not functioning in Xamarin WPF

### ISSUE THREAD

**Issue by Anish-V1073** [xamarin/Xamarin.Forms#9988]
### Steps to Reproduce

1.  Create a Picker with Background color set to some Color.
2. 
3. 

### Basic Information

- Version with issue: 4.5.0.396
- Last known good version:
- IDE: Visual studio 2017
- Platform Target Frameworks: 
 Xamarin.WPF 4.5.0.396
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: Windows device

**Comment by yurkinh** [comment]
@Anish-V1073  I think it is duplicate of #9838

**Comment by jfversluis** [comment]
Thanks @yurkinh!

This indeed seems a duplicate @Anish-V1073 thanks for reporting though! I will close this one, let's track the progress in the original issue. The good news is, @yurkinh also seems to have opened a PR to fix it, yay!

**Comment by jfversluis** [comment]
Duplicate of #9838
