### ISSUE TITLE
[Bug] [Android] [CollectionView]  Add new element to ItemSource bypasses VerticalItemSpacing

### ISSUE THREAD

**Issue by inimirpaz** [xamarin/Xamarin.Forms#9992]
### Description
When using a CollectionView on Android (iPhone works correctly) with "GridItemsLayout VerticalItemSpacing" > 0 the vertical spacing is ignored if the observed ItemSource gets a new element (e.g. ObservableCollection<T>.Add)
Refreshing the list (clear + add) solves the issue.

### Steps to Reproduce
1. Have a CollectionView with a DataTemplate for its items and GridItemsLayout with VerticalItemSpacing > 0 
2. Add new Items to the observed collection.

### Expected Behavior
New items added to the ItemSource must keep the vertical spacing among one another
![Screenshot_1584455887](https://user-images.githubusercontent.com/56956625/76868298-fa173800-6866-11ea-92d1-c63ddcaf92e4.png)

### Basic Information

- Version with issue: at least since 4.4 (Sample project runs XF 4.5.0.396)
- Last known good version: N.A.
- IDE: VS for Mac 8.4.8 (build 2)
- Platform Target Frameworks: devices with API 23 -> 28 for sure.
- Xamarin.Android: Version: 10.1.3.7 (Visual Studio Professional)
- Android Support Library Version: Recently added AndroidX

### Screenshots
![Screenshot_1584455880](https://user-images.githubusercontent.com/56956625/76868206-db18a600-6866-11ea-8ac3-bb7f034f2d1f.png)

### Reproduction Link
[CollectionViewBug2.zip](https://github.com/xamarin/Xamarin.Forms/files/4344000/CollectionViewBug2.zip)

### Workaround
Clear the observed ItemSource, add all items all over again.

**Comment by jfversluis** [comment]
Confirmed that this is happening, also on our latest nightly

**Comment by jfversluis** [comment]
Confirmed this is working as expected in current version
