### ISSUE TITLE
tab bar is simulated in preview but not in simulator

### ISSUE THREAD

**Issue by vsfeedback** [xamarin/Xamarin.Forms#9994]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/925873/tab-bar-is-simulated-in-preview-but-not-in-simulat.html)._

---
<p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/119781-screen-shot-2020-02-21-at-141114.png"></a><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/119782-screen-shot-2020-02-21-at-141130.png"></a>
</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/119782-screen-shot-2020-02-21-at-141130.png"></a></p><p>I would like to report a bug. I have attached 3 screenshot. In 1st screenshot I code tab view to display 4 tabs. It displays correctly on preview and simulator.</p> <p>1st screenshot:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/119781-screen-shot-2020-02-21-at-141114.png"> Image:119781-screen-shot-2020-02-21-at-141114.png</a>In 2nd screenshot I uncommented the 2nd last line so that I will have 5 tabs. In the preview it display correctly, but in the simulator after being rebuild and run it does not add the logout tab. </p> <p>2nd screenshot:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/119782-screen-shot-2020-02-21-at-141130.png"> Image:119782-screen-shot-2020-02-21-at-141130.png</a>In the 3rd screenshot I remove the icon property of the profile tab. In the preview and simulator after rebuild and run, it now show 5 tabs and also remove the profile Icon</p><p>3rd screenshot:</p><p><a href="https://developercommunityapi.westus.cloudapp.azure.com/storage/attachments/119783-screen-shot-2020-02-21-at-141201.png"></a><a href="https://developercommunity.visualstudio.com/storage/attachments/119784-screen-shot-2020-02-21-at-141201.png"> Image:119784-screen-shot-2020-02-21-at-141201.png</a>I run this on iphone 5s ios12.4 simulator but I have test on other simulator and the same issue happened</p>

---
#### Visual Studio Feedback System on 2/21/2020, 01:44 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

> VS bug [#1083874](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1083874)

**Comment by jfversluis** [comment]
Thanks for the report! I'm not really sure what the issue is you are describing. You mention both the previewer and the Simulator? So when you add tabs they do not show up whenever you run it in the Simulator? Or are you using Hot Reload? Seeing that you are using Windows for iOS development, maybe some kind of caching issue is involved. Be sure to really clean and rebuild the project and if all else fails delete the bin and obj folders from the filesystem and then rebuild to be sure that you have the latest code.

If the problem still shows, please add a reproduction project so we can have a look. Thanks!

**Comment by paymicro** [comment]
I could not reproduce this issue.
Without using a hot reload, everything looks fine
![Screenshot_9](https://user-images.githubusercontent.com/27482193/79600207-6fd52480-80ef-11ea-94e5-cec6efc536e8.png)

**Comment by samhouts** [comment]
Since we haven't heard from you in more than 30 days, we hope this issue is no longer affecting you. If it is, please reopen this issue and provide the requested information so that we can look into it further. Thank you!
