### ISSUE TITLE
[Bug] Xamarin.Forms 4.5.0.396 iOS FlexLayout and TemplateSelector issue

### ISSUE THREAD

**Issue by NebulaSleuth** [xamarin/Xamarin.Forms#9997]
### Description
When using a FlexLayout with a TemplateSelector, rendering of the items in the collection becomes corrupted when switching between different collections.

### Steps to Reproduce

1.  Create a page with a FlexLayout using BindableLayout.TemplateSelector with at least 2 different DataTemplates
2. Bind the FlexLayout to a collection of objects.
3. After displaying, change the collection of objects

### Expected Behavior
Displays each DataTemplate correctly

### Actual Behavior
Display is corrupted with overlapping renderings of DataTemplates

### Basic Information

- Version with issue:
4.5.0.396

- Last known good version:
4.4.0.991757

- IDE: VS 2019 16.4.6
- Platform Target Frameworks: 
  - iOS:  13.10.0.21
  - Android: No Issues
  - UWP:  No Issues
- Affected Devices: All iOS devices

### Screenshots
![Incorrectly Rendered](https://user-images.githubusercontent.com/5853441/76885197-181b7300-683c-11ea-9bf5-3e29238d44e0.png)
![Correctly Rendered](https://user-images.githubusercontent.com/5853441/76885202-1a7dcd00-683c-11ea-94ec-219152f7ee0a.png)

### Reproduction Link
[App1.zip](https://github.com/xamarin/Xamarin.Forms/files/4344888/App1.zip)

### Workaround
Downgrade to Xamarin.Forms 4.4

**Comment by NebulaSleuth** [comment]
The second image is displaying correctly which occurs when first running.  After clicking 'SWAP' button the first image is the result.

**Comment by NebulaSleuth** [comment]
Also, I ahev tried:
`            Xamarin.Forms.Forms.SetFlags("UseLegacyRenderers");

            global::Xamarin.Forms.Forms.Init();`

But the problem still occurs.

**Comment by yurkinh** [comment]
@NebulaSleuth  Workaround is to set "HasShadow=false" in 4.5.x version. Problem is with Frame not with FlexLayout

**Comment by NebulaSleuth** [comment]
@yurkinh  Thanks it works.
