### ISSUE TITLE
[Enhancement] Maunally set accessibility focus in Xamarin Forms 

### ISSUE THREAD

**Issue by rnic99** [xamarin/Xamarin.Forms#9999]
## Summary

On both Android and iOS a developer can decide to set the accessibility focus on an element of their choosing. 

This is done on iOS via UIAccessibilityPostNotification(UIAccessibilityLayoutChangedNotification, elementYouWantToFocus);. 

This is done on Android like so
elementYouWantToFocus.sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_FOCUSED);

## API Changes

AutomationProperties.SetFocus(elementYouWantToFocus, "Announcement on where focus was moved)"

## Intended Use Case

Useful for developers to help inform accessibility users that there has been a change on the page. Could be for specifically navigating a user to an error on the page, or telling them there is new content after clicking a checkbox or submitting a form.

**Comment by skadookkunnan** [comment]
It would be great to have this implemented. We are also stuck with a native implementation of not being able to do it from the Xamarin Forms directly.

Sincerely,
Sagar S. Kadookkunnan

**Comment by JTOne123** [comment]
This is my example of use case

```
    <StackLayout IsTabStop="True" TabIndex="7" Focused="Grid_Focused">

        <Entry Text="Entry0" TabIndex="0" IsTabStop="True" Grid.Row="0"></Entry>
        <Label Text="lable1" TabIndex="1" IsTabStop="True" Grid.Row="1" Focused="Label_Focused" AutomationProperties.IsInAccessibleTree="True" TextColor="Black"></Label>
        <Entry Text="Entry2" TabIndex="2" IsTabStop="True" Grid.Row="2"></Entry>
        <Label Text="lable3" TabIndex="3" IsTabStop="True" Grid.Row="3"  Focused="Label_Focused" AutomationProperties.IsInAccessibleTree="True" TextColor="Black"></Label>
        <Entry Text="Entry4" TabIndex="4" IsTabStop="True" Grid.Row="4"></Entry>
        <Label Text="lable5" TabIndex="5" IsTabStop="True" Grid.Row="5"  Focused="Label_Focused" AutomationProperties.IsInAccessibleTree="True" TextColor="Black"></Label>
        <Label Text="lable6" TabIndex="6" IsTabStop="True" Grid.Row="6"  Focused="Label_Focused" AutomationProperties.IsInAccessibleTree="True" TextColor="Black"></Label>

    </StackLayout>
```

Related topic in stackoverflow
https://stackoverflow.com/questions/54949444/xamarin-layout-cant-receive-focus

**Comment by johnshardman** [comment]
@rnic99 - Would you happen to know the UWP equivalent of those iOS and Android bits of code please?

I'm adding custom controls and custom renderers to implement this functionality as a workaround until it appears in XF or MAUI.

**Comment by djhango** [comment]
@johnshardman I believe the TryFocusAsync method of the [FocusManager](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmanager?view=winrt-19041#methods) should do what you are after

**Comment by rachelkang** [comment]
Hi folks! Thanks for all the feedback :)

We've [added this API in .NET MAUI](https://github.com/dotnet/maui/pull/1829) and will be bringing it to the XamarinCommunityToolkit shortly as well - https://github.com/xamarin/XamarinCommunityToolkit/issues/1711. If you have any feedback to share on how this new API meshes with your various scenarios, please feel free to share!

In the interim, feel free to check out https://github.com/PureWeen/A11YTools as well.
